version: "3"

services:
  dns:
    image: ragibkl/bancuh-dns
    restart: always
    privileged: true # For some reason, some distro needs this
    ports:
      - 1153:53/tcp
      - 1153:53/udp
    env_file: .env
    volumes:
      - ../../data:/local-data/
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"

  dnsdist:
    image: ragibkl/dnsdist-acme
    restart: always
    privileged: true # For some reason, some distro needs this
    network_mode: host
    env_file: .env
    environment:
      BACKEND: 127.0.0.1:1153
    volumes:
      - letsencrypt:/etc/letsencrypt
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"

volumes:
  letsencrypt:
